on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  test-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: kpk47/slsa-verifier/actions/installer@v0.0.17
  test-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: kpk47/slsa-verifier/actions/installer@a53b192e5b6649594c6441bcf3ce70f871d4e1d5
