on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  test-install:
    strategy:
      matrix:
        ref: ['v1.4.0', 'e6428d7da594455a4c2b7f24907fec421a5e0e95', 'v1.4.1', 'e6428d7da594455a4c2b7f24907fec421a5e0e95']
    runs-on: ubuntu-latest
    steps:
      - uses: slsa-framework/slsa-verifier/actions/installer@${{ matrix.ref }}
