on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  test-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: kpk47/slsa-verifier/actions/installer@v0.0.18
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
  test-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: kpk47/slsa-verifier/actions/installer@532af040baa96bf3c23bbe3b0e8fe3fd6b30a066
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
