on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  test-install:
    strategy:
      matrix:
        ref: ['v0.0.13', 'v0.0.14', 'f41d083a3804298adc912edec200293bce37eacb', 'e130d6ed7712826d9adfcd7e6f8cdbb8fbec637a']
    runs-on: ubuntu-latest
    steps:
      - uses: kpk47/slsa-verifier/actions/installer@${{ matrix.ref }}
